In [1]:
#importing the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("mobile_price_range_data.csv")
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [3]:
data.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [5]:
data.describe().T

count        mean          std    min      25%     50%  \
battery_power  2000.0  1238.51850   439.418206  501.0   851.75  1226.0   
blue           2000.0     0.49500     0.500100    0.0     0.00     0.0   
clock_speed    2000.0     1.52225     0.816004    0.5     0.70     1.5   
dual_sim       2000.0     0.50950     0.500035    0.0     0.00     1.0   
fc             2000.0     4.30950     4.341444    0.0     1.00     3.0   
four_g         2000.0     0.52150     0.499662    0.0     0.00     1.0   
int_memory     2000.0    32.04650    18.145715    2.0    16.00    32.0   
m_dep          2000.0     0.50175     0.288416    0.1     0.20     0.5   
mobile_wt      2000.0   140.24900    35.399655   80.0   109.00   141.0   
n_cores        2000.0     4.52050     2.287837    1.0     3.00     4.0   
pc             2000.0     9.91650     6.064315    0.0     5.00    10.0   
px_height      2000.0   645.10800   443.780811    0.0   282.75   564.0   
px_width       2000.0  1251.51550   432.199447  500.0   874.75  1247.0   
ram            2000.0  2124.21300  1084.732044  256.0  1207.50  2146.5   
sc_h           2000.0    12.30650     4.213245    5.0     9.00    12.0   
sc_w           2000.0     5.76700     4.356398    0.0     2.00     5.0   
talk_time      2000.0    11.01100     5.463955    2.0     6.00    11.0   
three_g        2000.0     0.76150     0.426273    0.0     1.00     1.0   
touch_screen   2000.0     0.50300     0.500116    0.0     0.00     1.0   
wifi           2000.0     0.50700     0.500076    0.0     0.00     1.0   
price_range    2000.0     1.50000     1.118314    0.0     0.75     1.5   

                   75%     max  
battery_power  1615.25  1998.0  
blue              1.00     1.0  
clock_speed       2.20     3.0  
dual_sim          1.00     1.0  
fc                7.00    19.0  
four_g            1.00     1.0  
int_memory       48.00    64.0  
m_dep             0.80     1.0  
mobile_wt       170.00   200.0  
n_cores           7.00     8.0  
pc               15.00    20.0  
px_height       947.25  1960.0  
px_width       1633.00  1998.0  
ram            3064.50  3998.0  
sc_h             16.00    19.0  
sc_w              9.00    18.0  
talk_time        16.00    20.0  
three_g           1.00     1.0  
touch_screen      1.00     1.0  
wifi              1.00     1.0  
price_range       2.25     3.0

# 1)Remove handle null values (if any).

In [6]:
data.isnull().sum()
#no null values

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

# 2)Split data into training and test data.

In [7]:
x = data.drop(["price_range"], axis=1)

y = data["price_range"]


In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25, random_state=0)

In [9]:
print(x_train.shape)
print(x_test.shape)

print(y_train.shape)
print(y_test.shape)

(1500, 20)
(500, 20)
(1500,)
(500,)


In [10]:
print(2000*0.1)
# 200 for testing 

200.0


# 3)Apply the following models on the training dataset and generate the predicted value for the test dataset
# 4)Predict the price range for test data
# 5)Compute Confusion matrix and classification report for each of these models.

# a) Logistic Regression

In [11]:
x_train.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1045            531     0          1.1         0  10       0          63   
937             764     1          1.2         1   1       0          13   
1658           1812     1          1.3         1   4       1          42   
529            1821     0          0.9         0   9       1          12   
895            1790     1          2.3         1   3       1          49   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
1045    0.7        189        7  14        145      1903  2958    17     1   
937     1.0        152        8   2        361       511  3148    18     7   
1658    1.0        162        7  15        380      1550  3338    18    13   
529     0.3        114        1  18         97      1803  2430     7     4   
895     0.5        100        3  11        396      1980  3568     6     2   

      talk_time  three_g  touch_screen  wifi  
1045         19        0             1     0  
937           6        1             1     0  
1658         11        1             1     1  
529           6        1             1     1  
895          18        1             0     1

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
m1 = LogisticRegression()
m1.fit(x_train,y_train)

C:\Users\manju\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [14]:
print('Model Training Score',m1.score(x_train,y_train))
print('Model Testing Score',m1.score(x_test,y_test))

Model Training Score 0.6326666666666667
Model Testing Score 0.65


In [15]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

[3 0 2 1 3 0 0 2 2 2 1 3 0 1 2 0 3 2 2 1 1 0 3 2 1 2 3 1 3 1 2 0 1 1 2 3 0
 0 3 2 3 3 3 3 2 2 0 1 3 1 0 2 0 3 0 3 3 1 0 3 3 2 2 1 1 3 3 3 2 2 3 2 1 0
 1 3 3 1 1 1 3 1 3 0 0 0 1 0 1 3 1 2 1 1 0 3 2 3 0 2 1 2 2 0 3 2 3 2 3 3 2
 0 0 2 3 3 1 0 1 0 0 3 2 2 1 2 0 1 0 3 1 3 3 2 3 3 3 3 0 1 1 3 2 3 0 3 0 0
 2 0 1 1 1 1 3 0 0 3 1 3 1 2 2 1 3 3 3 3 0 1 3 2 1 3 3 0 1 1 3 0 3 1 0 1 2
 1 3 0 3 3 3 3 1 1 2 1 0 2 2 0 3 3 3 0 1 3 2 2 0 0 0 2 2 2 0 0 0 2 2 2 2 3
 0 0 3 3 2 2 0 3 1 0 0 3 2 0 2 2 0 0 0 2 3 2 0 0 2 3 3 1 3 0 2 1 1 0 1 2 3
 2 0 0 1 3 3 3 2 3 3 2 1 2 2 2 1 3 2 2 2 1 0 2 1 0 0 0 1 3 3 3 0 1 2 0 2 2
 3 0 1 0 1 1 3 0 0 1 3 1 2 1 1 0 3 0 2 3 2 2 0 1 3 1 0 1 0 1 0 3 1 2 2 0 0
 2 3 0 3 1 1 0 1 3 0 2 1 1 2 2 2 0 3 0 0 2 1 2 3 2 2 0 3 2 3 2 2 2 2 3 3 0
 2 1 1 0 1 1 2 2 1 3 1 1 0 1 1 3 1 0 0 3 0 3 0 2 3 1 1 0 2 1 0 0 3 0 3 3 0
 3 3 3 2 2 3 2 1 3 1 2 1 0 2 1 1 1 1 3 1 2 2 0 3 1 1 1 3 0 2 3 2 2 2 3 0 0
 1 2 1 2 0 3 3 0 3 3 0 3 1 2 0 2 2 0 3 3 2 0 2 0 3 3 2 2 1 3 1 2 0 1 1 3 0
 2 0 0 1 3 0 1 2 0 3 3 3 

In [16]:
from sklearn.metrics import confusion_matrix,classification_report

In [17]:
cm=confusion_matrix(y_test,ypred_m1)
print(cm)
print(classification_report(y_test,ypred_m1))

[[104  18   2   0]
 [ 17  63  25   5]
 [  0  33  58  34]
 [  0   2  39 100]]
              precision    recall  f1-score   support

           0       0.86      0.84      0.85       124
           1       0.54      0.57      0.56       110
           2       0.47      0.46      0.47       125
           3       0.72      0.71      0.71       141

    accuracy                           0.65       500
   macro avg       0.65      0.65      0.65       500
weighted avg       0.65      0.65      0.65       500



# b) KNN Classification

In [18]:
x = data.iloc[:,:-1]
y = data.iloc[:,-1]
print(x.shape)
print(y.shape)

(2000, 20)
(2000,)


In [19]:
x.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2   2         20       756  2549     9     7         19   
1        136        3   6        905      1988  2631    17     3          7   
2        145        5   6       1263      1716  2603    11     2          9   
3        131        6   9       1216      1786  2769    16     8         11   
4        141        2  14       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  
0        0             0     1  
1        1             1     0  
2        1             1     0  
3        1             0     0  
4        1             1     0

In [20]:
y.head()

0    1
1    2
2    2
3    2
4    1
Name: price_range, dtype: int64

In [21]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
m2 = KNeighborsClassifier(n_neighbors=11)
m2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=11)

In [23]:
print('Training score',m2.score(x_train,y_train))
print('Testing score',m2.score(x_test,y_test))

Training score 0.9466666666666667
Testing score 0.942


In [24]:
ypred_m2 = m2.predict(x_test)
print(ypred_m2)

[3 0 2 2 2 0 0 2 3 1 0 3 0 2 3 0 3 2 2 1 0 0 3 1 2 2 3 1 3 1 1 0 2 0 1 3 0
 0 3 3 3 1 3 3 1 3 0 1 3 1 1 3 0 3 0 2 2 2 0 3 3 1 3 2 1 2 3 2 2 2 3 2 1 0
 1 3 2 1 1 2 3 3 3 0 0 0 2 1 2 3 1 2 2 1 0 3 2 3 0 3 1 1 2 1 3 2 2 3 2 3 3
 0 0 1 2 3 0 0 1 0 0 3 2 2 1 1 1 1 0 2 1 3 3 3 3 3 3 2 0 1 1 2 1 3 0 3 0 0
 2 0 1 1 1 1 3 0 0 3 1 3 2 1 3 1 2 3 3 3 1 0 3 1 2 3 3 0 2 2 3 0 2 1 0 1 2
 2 2 0 3 3 1 1 0 2 3 0 1 2 2 0 3 3 3 1 2 3 3 3 1 0 0 2 3 3 0 0 1 3 1 3 3 3
 0 0 2 2 3 1 0 2 0 0 0 3 3 0 2 2 1 1 0 2 3 3 0 0 1 3 3 2 3 0 3 1 1 0 2 3 3
 2 0 0 1 2 3 2 2 3 1 1 0 3 3 2 1 3 3 2 2 1 0 2 2 1 0 0 2 2 2 2 0 1 3 0 1 2
 3 0 2 0 1 1 3 0 0 1 3 1 2 0 2 0 3 0 3 3 2 3 1 2 2 1 1 1 0 1 0 3 1 0 3 0 0
 1 2 0 3 1 2 0 1 3 0 2 2 1 2 1 1 0 2 0 0 3 1 2 3 2 2 0 3 2 2 1 3 2 3 3 3 0
 2 0 3 0 1 1 2 2 1 2 1 2 0 1 2 3 0 0 1 3 0 3 0 1 2 1 1 0 3 1 0 1 3 0 3 3 0
 2 1 3 2 1 3 2 0 3 3 2 0 0 3 0 1 1 1 3 2 3 2 0 3 0 0 1 3 0 0 3 3 2 2 3 0 0
 1 2 1 2 0 3 3 0 2 3 0 3 2 1 0 2 2 1 3 2 2 0 2 0 3 3 2 1 0 3 0 2 0 0 1 3 0
 3 0 0 1 2 0 1 3 0 2 2 1 

In [25]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [26]:
cm = confusion_matrix(y_test, ypred_m2)
print(cm)

[[123   1   0   0]
 [  4 104   2   0]
 [  0   5 112   8]
 [  0   0   9 132]]


In [27]:
print(classification_report(y_test, ypred_m2))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       124
           1       0.95      0.95      0.95       110
           2       0.91      0.90      0.90       125
           3       0.94      0.94      0.94       141

    accuracy                           0.94       500
   macro avg       0.94      0.94      0.94       500
weighted avg       0.94      0.94      0.94       500



# c) SVM Classifier with linear and rbf kernel

In [28]:
x = data.iloc[:,:-1]
y = data.iloc[:,-1]
print(x.shape)
print(y.shape)

(2000, 20)
(2000,)


In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [31]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1500, 20)
(500, 20)
(1500,)
(500,)


In [32]:
from sklearn.svm import SVC

In [33]:
m3 = SVC(kernel='linear',C=1)
m3 = m3.fit(x_train,y_train)

In [34]:
print('Training score',m3.score(x_train,y_train))
print('Testing score',m3.score(x_test,y_test))

Training score 0.9933333333333333
Testing score 0.964


In [40]:
ypred_m3 = m3.predict(x_test)
print(ypred_m3)

[1 1 2 0 0 0 3 0 3 1 0 1 0 1 2 1 1 3 2 1 3 1 2 1 2 1 1 3 3 0 2 0 0 1 0 0 2
 3 3 0 3 2 3 3 3 2 2 0 1 3 2 3 0 1 3 3 0 1 3 0 0 1 0 3 0 3 2 0 0 2 3 1 3 2
 0 0 1 1 0 0 3 0 0 1 0 1 1 1 3 1 2 2 0 2 3 2 3 0 1 0 1 1 2 2 1 3 0 2 2 2 1
 2 2 1 3 1 2 3 1 1 1 2 1 2 3 2 1 2 1 2 3 3 0 0 2 0 1 1 3 3 3 3 1 2 3 3 3 2
 2 1 1 1 1 3 2 3 3 0 0 3 0 0 2 0 0 1 1 3 2 0 3 1 1 3 3 1 0 1 1 2 3 0 0 3 1
 3 0 0 3 3 3 1 2 0 1 3 2 1 2 1 3 0 0 1 3 3 0 3 3 3 1 2 1 3 1 3 1 2 3 1 1 1
 0 2 2 0 3 3 2 3 3 1 3 1 1 1 2 0 3 0 1 3 2 3 2 0 3 2 3 2 0 1 1 0 2 1 2 3 0
 1 1 2 0 0 2 2 1 2 2 3 1 3 2 2 2 1 3 3 2 0 2 3 1 1 1 3 1 1 1 3 2 2 2 3 1 3
 3 3 0 3 1 1 3 2 3 0 0 0 0 0 0 1 2 0 0 2 3 2 0 1 3 1 2 0 3 3 3 1 3 3 0 1 3
 0 3 3 0 3 1 1 0 0 2 1 2 0 1 2 1 0 1 2 3 0 0 0 3 1 2 0 1 1 3 3 3 3 3 3 1 2
 2 2 0 0 2 3 1 1 2 2 2 2 1 0 0 0 2 3 1 0 0 2 2 2 0 3 1 3 3 2 0 1 2 2 2 1 3
 0 3 2 3 2 2 1 2 1 3 3 0 3 3 1 3 0 2 1 2 1 2 0 3 3 3 0 3 2 0 3 3 3 2 2 2 3
 0 3 2 2 3 2 2 1 3 3 2 1 0 2 3 3 3 3 0 1 3 0 0 0 0 1 2 1 0 2 3 3 0 2 2 2 0
 0 1 3 1 1 3 3 2 0 2 1 1 

In [41]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [42]:
def eval_metrics(ytest, ypred):
    cm = confusion_matrix(ytest,ypred)
    print(cm)
    print(classification_report(ytest,ypred))

In [43]:
eval_metrics(y_test,ypred_m3)

[[113   2   0   0]
 [  3 119   1   0]
 [  0   3 117   8]
 [  0   0   1 133]]
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       115
           1       0.96      0.97      0.96       123
           2       0.98      0.91      0.95       128
           3       0.94      0.99      0.97       134

    accuracy                           0.96       500
   macro avg       0.97      0.96      0.96       500
weighted avg       0.96      0.96      0.96       500



In [44]:
m4 = SVC(kernel='rbf',gamma=10,C=10)
m4.fit(x_train,y_train)

SVC(C=10, gamma=10)

In [45]:
print('Training score',m4.score(x_train,y_train))
print('Testing score',m4.score(x_test,y_test))

Training score 1.0
Testing score 0.23


In [46]:
ypred_m4 = m4.predict(x_test)
print(ypred_m4)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [47]:
eval_metrics(y_test,ypred_m4)

[[115   0   0   0]
 [123   0   0   0]
 [128   0   0   0]
 [134   0   0   0]]
              precision    recall  f1-score   support

           0       0.23      1.00      0.37       115
           1       0.00      0.00      0.00       123
           2       0.00      0.00      0.00       128
           3       0.00      0.00      0.00       134

    accuracy                           0.23       500
   macro avg       0.06      0.25      0.09       500
weighted avg       0.05      0.23      0.09       500



C:\Users\manju\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\manju\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\manju\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 6)Report the model with the best accuracy.

the best accuracy model is SVM Classifier with linear than the logistic regression model , KNN classification model, SVM Classifier with rbf kernal for 25 percent testing dataset. because the accuracy of SVM Classifier with linear is 0.97. so SVM Classifier with linear is the best model

In [48]:
from sklearn.svm import SVC

In [49]:
m3 = SVC(kernel='linear',C=1)
m3 = m3.fit(x_train,y_train)

In [50]:
print('Training score',m3.score(x_train,y_train))
print('Testing score',m3.score(x_test,y_test))

Training score 0.9933333333333333
Testing score 0.964


In [51]:
ypred_m3 = m3.predict(x_test)
print(ypred_m3)

[1 1 2 0 0 0 3 0 3 1 0 1 0 1 2 1 1 3 2 1 3 1 2 1 2 1 1 3 3 0 2 0 0 1 0 0 2
 3 3 0 3 2 3 3 3 2 2 0 1 3 2 3 0 1 3 3 0 1 3 0 0 1 0 3 0 3 2 0 0 2 3 1 3 2
 0 0 1 1 0 0 3 0 0 1 0 1 1 1 3 1 2 2 0 2 3 2 3 0 1 0 1 1 2 2 1 3 0 2 2 2 1
 2 2 1 3 1 2 3 1 1 1 2 1 2 3 2 1 2 1 2 3 3 0 0 2 0 1 1 3 3 3 3 1 2 3 3 3 2
 2 1 1 1 1 3 2 3 3 0 0 3 0 0 2 0 0 1 1 3 2 0 3 1 1 3 3 1 0 1 1 2 3 0 0 3 1
 3 0 0 3 3 3 1 2 0 1 3 2 1 2 1 3 0 0 1 3 3 0 3 3 3 1 2 1 3 1 3 1 2 3 1 1 1
 0 2 2 0 3 3 2 3 3 1 3 1 1 1 2 0 3 0 1 3 2 3 2 0 3 2 3 2 0 1 1 0 2 1 2 3 0
 1 1 2 0 0 2 2 1 2 2 3 1 3 2 2 2 1 3 3 2 0 2 3 1 1 1 3 1 1 1 3 2 2 2 3 1 3
 3 3 0 3 1 1 3 2 3 0 0 0 0 0 0 1 2 0 0 2 3 2 0 1 3 1 2 0 3 3 3 1 3 3 0 1 3
 0 3 3 0 3 1 1 0 0 2 1 2 0 1 2 1 0 1 2 3 0 0 0 3 1 2 0 1 1 3 3 3 3 3 3 1 2
 2 2 0 0 2 3 1 1 2 2 2 2 1 0 0 0 2 3 1 0 0 2 2 2 0 3 1 3 3 2 0 1 2 2 2 1 3
 0 3 2 3 2 2 1 2 1 3 3 0 3 3 1 3 0 2 1 2 1 2 0 3 3 3 0 3 2 0 3 3 3 2 2 2 3
 0 3 2 2 3 2 2 1 3 3 2 1 0 2 3 3 3 3 0 1 3 0 0 0 0 1 2 1 0 2 3 3 0 2 2 2 0
 0 1 3 1 1 3 3 2 0 2 1 1 

In [52]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [53]:
def eval_metrics(ytest, ypred):
    cm = confusion_matrix(ytest,ypred)
    print(cm)
    print(classification_report(ytest,ypred))


In [54]:
eval_metrics(y_test,ypred_m3)

[[113   2   0   0]
 [  3 119   1   0]
 [  0   3 117   8]
 [  0   0   1 133]]
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       115
           1       0.96      0.97      0.96       123
           2       0.98      0.91      0.95       128
           3       0.94      0.99      0.97       134

    accuracy                           0.96       500
   macro avg       0.97      0.96      0.96       500
weighted avg       0.96      0.96      0.96       500



# conclusion :
the best accuracy model is SVM Classifier with linear because the accuracy of SVM Classifier with linear is 0.97. so SVM Classifier with linear is the best model